# Generated by Django 2.0.6 on 2018-06-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180616_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
