# Generated by Django 2.0.6 on 2018-06-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180617_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
